const { Book } = require("./models");

require("./config/db.connection")

Book.insertMany(
    [
        {
            username: "oks",
            title: "Life of Pi",
            author: "Yann Martel",
            year: 2001,
            genre: "Fantasy adventure novel",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1631251689l/4214._SY475_.jpg",
            pages: 352,
            audioBook: 13,
            readingStatus: "wanttoread",
            notes: "Yann Martel's third novel, Life of Pi (2001), follows protagonist Piscine “Pi” Patel on a journey of survival after the cargo ship carrying him and his family sinks in the Pacific Ocean. "
        },
        {
            username: "oks",
            title: "Dial A for Aunties",
            author: "Jesse Q. Sutanto",
            year: 2021,
            genre: "Crime, Romance, Comedy",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1601307658l/53310061.jpg",
            pages: 299,
            audioBook: "12",
            readingStatus: "read",
            notes: "This is the perfect summer read! This book was a lovely surprise! It's a little more romance than I was expecting, but I had so much fun with this story from beginning to end. "
        },

        {
            username: "oks",
            title: "How Y'all Doing?: Misadventures and Mischief from a Life Well Lived",
            author: "Leslie Jordan",
            year: 2021,
            genre: "Humor",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1611776582l/55339007.jpg",
            pages: 208,
            audioBook: 5,
            readingStatus: "wanttoread",
            notes: "Viral sensation and Emmy Award-winner Leslie Jordan regales fans with entertaining stories about the odd, funny, and unforgettable events in his life in this unmissable essay collection that echoes his droll, irreverent voice.",
        },
        {
            username: "oks",
            title: "Two Heads: A Graphic Exploration of How Our Brains Work with Other Brains",
            author: "Uta Frith, Chris Frith",
            year: 2022,
            genre: "Psychology, Novel",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1649384674l/58437575._SX318_.jpg",
            pages: 352,
            audioBook: 13,
            readingStatus: "wanttoread",
            notes: "A lively, accessible, graphic novel that takes us on a highly entertaining and fascinating tour through the wonders and mysteries of the human brain—from a renowned husband-and-wife team of cognitive neuroscientists.",
        },
        {
            username: "oks",
            title: "The A.B.C. Murders",
            author: "Agatha Christie",
            year: 1936,
            genre: "Mystery, Novel, Crime Fiction",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1389733983l/16322.jpg",
            pages: 232,
            audioBook: 8,
            readingStatus: "wanttoread",
            notes: "Agatha Christie is such a crafty devil that midway through a novel she might have you believing that YOU are the murderer!",
        },
        {
            username: "oks",
            title: "A Molecule Away from Madness: Tales of the Hijacked Brain",
            author: "Sara Manning Peskin",
            year: 2022,
            genre: "Psychology",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1641271142l/58085250.jpg",
            pages: 224,
            audioBook: 8,
            readingStatus: "wanttoread",
            notes: "Our brains are the most complex machines known to humankind, but they have an Achilles heel: the very molecules that allow us to exist can also sabotage our minds. Here are gripping accounts of unruly molecules and the diseases that form in their wake.",
        },
        {
            username: "oks",
            title: "One Italian Summer",
            author: "Rebecca Serle",
            year: 2022,
            genre: "Romance novel",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1626799802l/58438583.jpg",
            pages: 272,
            audioBook: 9,
            readingStatus: "reading",
            notes: "The author created another emotional, moving, powerful story located in dreamy Italian island with three dimensional, well-developed, easily connectable characters. There are impressively depicted landscapes and mouth watering food which are also tempting to enjoy our reading journey! This is purely effective story questions meaning of life, friendship, self growth, our purposes, dreams, regrets!",
        },
        {
            username: "oks",
            title: "Ten Steps to Nanette",
            author: "Hannah Gadsby",
            year: 2022,
            genre: "Biography, Autobiography, Humor",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1637305486l/40588534._SY475_.jpg",
            pages: 400,
            audioBook: 16,
            readingStatus: "reading",
            notes: "Multi-awardwinning Hannah Gadsby transformed comedy with her show Nanette, even as she declared that she was quitting stand-up. Now, she takes us through the defining moments in her life that led to the creation of Nanette and her powerful decision to tell the truth-no matter the cost.",
        },
        {
            username: "oks",
            title: "Woman on Fire",
            author: "Lisa Barr",
            year: 2022,
            genre: "Historical fiction, Thriller",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1639377419l/58275730.jpg",
            pages: 416,
            audioBook: 16,
            readingStatus: "reading",
            notes: "History. Stolen art. Family secrets. Psychopaths. European settings. This book has it all and then some. Compelling and rich, twisted and devious, I devoured it in a matter of days.",
        },
        {
            username: "oks",
            title: "The Power of Regret: How Looking Backward Moves Us Forward",
            author: "Daniel H. Pink",
            year: 2022,
            genre: "Self-help book, Business",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1631506945l/58446721.jpg",
            pages: 239,
            audioBook: 8,
            readingStatus: "reading",
            notes: "Everybody has regrets, Daniel H. Pink explains in The Power of Regret. They're a universal and healthy part of being human. And understanding how regret works can help us make smarter decisions, perform better at work and school, and bring greater meaning to our lives.",
        },
        {
            username: "oks",
            title: "Numbers Don't Lie: 71 Things You Need to Know About the World",
            author: "Vaclav Smil",
            year: 2020,
            genre: "Non-fiction",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1598804527l/50705179._SY475_.jpg",
            pages: 384,
            audioBook: 13,
            readingStatus: "reading",
            notes: "Is flying dangerous? How much do the world's cows weigh? And what makes people happy? From earth's nations and inhabitants, through the fuels and foods that energize them, to the transportation and inventions of our modern world - and how all of this affects the planet itself - in Numbers Don't Lie, Professor Vaclav Smil takes us on a fact-finding adventure, using surprising statistics and illuminating graphs to challenge lazy thinking.",
        },
        {
            username: "oks",
            title: "Fahrenheit 451",
            author: "Ray Bradbury",
            year: 1953,
            genre: "Novel, Science Fiction, Dystopian Fiction",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1383718290l/13079982.jpg",
            pages: 194,
            audioBook: 7,
            readingStatus: "read",
            notes: "The burning of books is such an effective tool for controlling the population, so the message of Ray Bradbury's Fahrenheit 451 is scarily real. If society's wisdom could be taken away, then so could their freedom. If knowledge was burnt, then the people would be left in a complete state of utter innocent ignorance. ",
        },
        {
            username: "oks",
            title: "The Great Gatsby",
            author: "F. Scott Fitzgerald",
            year: 1925,
            genre: "Novel, Tragedy, Psychological Fiction",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1490528560l/4671._SY475_.jpg",
            pages: 200,
            audioBook: 8,
            readingStatus: "read",
            notes: "Fitzgerald can set a scene so perfectly, flawlessly. He paints a world of magic and introduces one of the greatest characters of all time, Jay Gatsby. Gatsby is the embodiment of hope, and no one can dissuade him from his dreams. Have you ever had a dream that carried you to heights you could never have dreamed otherwise? ",
        },
        {
            username: "oks",
            title: "The Catcher in the Rye",
            author: " J.D. Salinger",
            year: 1951,
            genre: "Novel, Literary Realism",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1398034300l/5107.jpg",
            pages: 277,
            audioBook: 9,
            readingStatus: "read",
            notes: "This book can change peopele's lives and helpe them find their unique way in the world",
        },
        {
            username: "oks",
            title: "The Old Man and the Sea",
            author: "Ernest Hemingway",
            year: 1952,
            genre: "Novel, Nautical Fiction",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1329189714l/2165._SY475_.jpg",
            pages: 8,
            audioBook: 13,
            readingStatus: "read",
            notes: "This short novel, already a modern classic, is the superbly told, tragic story of a Cuban fisherman in the Gulf Stream and the giant Marlin he kills and loses—specifically referred to in the citation accompanying the author's Nobel Prize for literature in 1954",
        },

        {
            username: "alex",
            title: "What Happened to the Bennetts",
            author: "Lisa Scottoline",
            year: 2022,
            genre: "Mystery, Thriller ",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1632489470l/58502351.jpg",
            pages: "391",
            audioBook: "15",
            readingStatus: "read",
            notes: "Your family has been attacked, never again to be the same.Now you have to choose between law…and justice."
        },
        {
            username: "alex",
            title: "Star Wars: The High Republic: Light of the Jedi",
            author: "Charles Soule",
            year: 2021,
            genre: "Science Fiction",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1582619576l/51637946.jpg",
            pages: 380,
            audioBook: "14",
            readingStatus: "wanttoread",
            notes: "A good start to the new era of the Star Wars. A lot of new characters, old worlds but in a new setting. I did find the book a bit slow, but that is understandable as they are creating a new world."
        },
        {
            username: "alex",
            title: "The 5 AM Club: Own Your Morning. Elevate Your Life",
            author: "Robin S. Sharma",
            year: 2018,
            genre: "Creative non-fiction, Self-help book",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1545910967l/37502596._SY475_.jpg",
            pages: 336,
            audioBook: 12,
            readingStatus: "wanttoread",
            notes: "Legendary leadership and elite performance expert Robin Sharma introduced The 5am Club concept over twenty years ago, based on a revolutionary morning routine that has helped his clients maximize their productivity, activate their best health and bulletproof their serenity in this age of overwhelming complexity.",
        },
        {
            username: "alex",
            title: "Never Simple",
            author: "Liz Scheier ",
            year: 2022,
            genre: "Biography, Autobiography",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1629825092l/57771194.jpg",
            pages: 288,
            audioBook: 11,
            readingStatus: "wanttoread",
            notes: "Liz Scheier's darkly funny and touching memoir—with shades of Jeannette Walls's The Glass Castle and Mira Bartók's The Memory Palace—of growing up in '90s Manhattan with a brilliant, mendacious single mother",
        },
        {
            username: "alex",
            title: "The Perfect Other: A Memoir of My Sister",
            author: "Kyleigh Leddy ",
            year: 2022,
            genre: "Biography, Autobiography",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1627615268l/55959476.jpg",
            pages: 304,
            audioBook: 12,
            readingStatus: "wanttoread",
            notes: "All Kait Leddy had ever wanted was a little sister. When Kyleigh was born, they were inseparable; Kait would protect her, include her, cuddle and comfort her, and, to Kyleigh, her big sister was her whole world. Then, in January 2014, Kait disappeared...",
        },
        {
            username: "alex",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "wanttoread",
            notes: "",
        },
        {
            username: "alex",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "reading",
            notes: "",
        },
        {
            username: "alex",
            title: "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
            author: " James Clear",
            year: 2018,
            genre: "Creative non-fiction, Self-help book",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1535115320l/40121378._SY475_.jpg",
            pages: 319,
            audioBook: 12,
            readingStatus: "reading",
            notes: "If you're having trouble changing your habits, the problem isn't you. The problem is your system. Bad habits repeat themselves again and again not because you don't want to change, but because you have the wrong system for change. You do not rise to the level of your goals. You fall to the level of your systems. Here, you'll get a proven system that can take you to new heights.",
        },
        {
            username: "alex",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "reading",
            notes: "",
        },
        {
            username: "alex",
            title: "The War That Made the Roman Empire: Antony, Cleopatra, and Octavian at Actium",
            author: "Barry S. Strauss",
            year: 2022,
            genre: "Biography",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1647789396l/55711554._SY475_.jpg",
            pages: 368,
            audioBook: 13,
            readingStatus: "reading",
            notes: "The gripping story of one of history's most important and yet little-known wars, the campaign culminating in the Battle of Actium in 31 BC, whose outcome determined the future of the Roman Empire.",
        },
        {
            username: "alex",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "reading",
            notes: "",
        },
        {
            username: "alex",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "read",
            notes: "",
        },
        {
            username: "alex",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "read",
            notes: "",
        },
        {
            username: "alex",
            title: "Four Thousand Weeks: Time Management for Mortals",
            author: "Oliver Burkeman",
            year: 2021,
            genre: "Creative non-fiction, Self-help book",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1627425434l/54785515._SY475_.jpg",
            pages: 288,
            audioBook: 11,
            readingStatus: "read",
            notes: "First of all, this is probably not the book you think it is, and that's a good thing. Rather than offering cheap “time hacks” to get more of the same things done, this more philosophical work is based on two important but uncomfortable truths: (1) In the short 4,000 or so weeks you have to live, you will never be able to accomplish all the things you would like, and (2) even if you could, it wouldn't matter in the end because, in the words of John Maynard Keynes, “In the long run we are all dead.”",
        },
        {
            username: "alex",
            title: "To the Front!: Clara Barton Braves the Battle of Antietam",
            author: "Claudia Friddell",
            year: 2022,
            genre: "Biography",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1627327976l/57927126._SX318_.jpg",
            pages: 40,
            audioBook: 1,
            readingStatus: "read",
            notes: "This powerful tribute to Clara Barton and her heroic efforts during the Civil War's Battle of Antietam reveals how she earned the name The Angel of the Battlefield, and shows the beginnings of her journey as one of our country's greatest humanitarians and the founder of the American Red Cross.",
        },

        {
            username: "anthony",
            title: "Beautiful World, Where Are You",
            author: "Sally Rooney ",
            year: 2021,
            genre: "Epistolary novel, Urban fiction",
            cover: "https://images.randomhouse.com/cover/9780735281790",
            pages: 356,
            audioBook: "14",
            readingStatus: "read",
            notes: "She touches on modernism, capitalism, consumerism and waste, and living boldly in a world that seems to be falling apart."
        },

        {
            username: "anthony",
            title: "The Code Breaker: Jennifer Doudna, Gene Editing, and the Future of the Human Race",
            author: "Walter Isaacson",
            year: 2021,
            genre: "History and Biography",
            cover: "https://images.randomhouse.com/cover/9780735281790",
            pages: 536,
            audioBook: 18,
            readingStatus: "wanttoread",
            notes: "Quite good biography book"
        },
        {
            username: "anthony",
            title: "Talking to Strangers: What We Should Know About the People We Don't Know",
            author: "Malcolm Gladwell",
            year: 2019,
            genre: "Nonfiction",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1549393502l/43848929._SX318_.jpg",
            pages: 388,
            audioBook: 15,
            readingStatus: "wanttoread",
            notes: "Malcolm Gladwell, host of the podcast Revisionist History and author of the #1 New York Times bestseller Outliers, offers a powerful examination of our interactions with strangers -- and why they often go wrong.",
        },
        {
            username: "anthony",
            title: "Comedy Comedy Comedy Drama",
            author: "Bob Odenkirk",
            year: 2022,
            genre: "Biography",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1646255336l/60538221._SX318_.jpg",
            pages: 304,
            audioBook: 13,
            readingStatus: "wanttoread",
            notes: "In this hilarious, heartfelt memoir, the star of Mr. Show, Breaking Bad, Better Call Saul, and Nobody opens up about the highs and lows of showbiz, his legendary cult status as a comedy writer, and what it's like to reinvent himself as a no-holds-barred action film ass-kicker at fifty.",
        },
        {
            username: "anthony",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "wanttoread",
            notes: "",
        },
        {
            username: "anthony",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "wanttoread",
            notes: "",
        },
        {
            username: "anthony",
            title: "Creativity: A Short and Cheerful Guide",
            author: "John Cleese",
            year: 2020,
            genre: "Humor, Self-Help Book",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1599059150l/50719532._SY475_.jpg",
            pages: 112,
            audioBook: 4,
            readingStatus: "reading",
            notes: "Creativity is usually regarded as a mysterious, rare gift that only a few possess. John Cleese begs to differ, and in this short, immensely practical and often very amusing guide he shows it's a skill that anyone can acquire. Drawing on his lifelong experience as a writer, he shares his insights into the nature of the creative process, and offers advice on how to get your own inventive juices flowing.",
        },
        {
            username: "anthony",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "reading",
            notes: "",
        },
        {
            username: "anthony",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "reading",
            notes: "",
        },
        {
            username: "anthony",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "reading",
            notes: "",
        },
        {
            username: "anthony",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "reading",
            notes: "",
        },
        {
            username: "anthony",
            title: "Hero on a Mission: The Power of Finding Your Role in Life",
            author: "Donald Miller",
            year: 2022,
            genre: "Self-Help Book",
            cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1631508850l/57468174.jpg",
            pages: 224,
            audioBook: 8,
            readingStatus: "read",
            notes: "There are four roles we play in life—Victim, Villain, Hero, and Guide. New York Times bestselling author Donald Miller teaches us how to recognize when we are playing the Victim or the Villain and how to shift to become the Hero or the Guide.",
        },
        {
            username: "anthony",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "read",
            notes: "",
        },
        {
            username: "anthony",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "read",
            notes: "",
        },
        {
            username: "anthony",
            title: "",
            author: "",
            year: 8,
            genre: "",
            cover: "",
            pages: 8,
            audioBook: 13,
            readingStatus: "read",
            notes: "",
        },

    ],
    function (error, createdBooks) {
        if (error) {
            return console.log(error);
        }
        console.log("=== Seed Complete ===");
        console.log(createdBooks);
    }
);